version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

temporal:
  address: "temporal:7233"
  activities:
    num_workers: 4
    supervisor:
      ttl: 180s # 3 minutes

logs:
  level: debug
  mode: development
